apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgrest-cert
spec:
  secretName: postgrest-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: dxddb.casper.dev
  dnsNames:
    - dxddb.casper.dev
