apiVersion: v1
kind: ConfigMap
metadata:
  name: dxdprojects-config
data:
  CASPER_PARSER_DATABASE: "postgres://postgres@dxddb-service:5432/dxd"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgrest-config
data:
  PGRST_DB_URI: "postgres://postgres@dxddb-service:5432/dxd"
  PGRST_DB_SCHEMA: "public"
  PGRST_DB_ANON_ROLE: "web_anon"
  PGRST_OPENAPI_MODE: "ignore-privileges"
  PGRST_OPENAPI_SERVER_PROX_URI: "https://dxddb.casper.dev/swagger"
  PGRST_DB_MAX_ROWS: "100"
